[package]
name = "create_graphene"
version = "0.2.1"
authors = ["Petter Johansson <pettjoha@kth.se>"]
description = "Create a graphene substrate and output it to a GROMOS formatted file"

[dependencies]
clap = "2.22"
