[package]
name = "grafen"
version = "0.3.1"
authors = ["Petter Johansson <pettjoha@kth.se>"]
description = "Create graphene and other substrates for use in molecular dynamics simulations."
repository = "https://github.com/pjohansson/grafen"
travis-ci = { repository = "https://travis-ci.org/pjohansson/grafen", branch = "master"}
categories = ["command-line-utilities", "science"]
keywords = ["gromacs", "molecular-dynamics", "substrates"]
readme = "README.md"
license = "Unlicense"

[dependencies]
ansi_term = "^0.9.0"
clap = "~2.23.0"
