[package]
name = "create_system"
version = "0.3.0"
authors = ["Petter Johansson <pettjoha@kth.se>"]
description = "Create substrates and output to GROMOS formatted files"

[dependencies]
clap = "2.22"
