[package]
name = "create_system"
version = "0.3.0"
authors = ["Petter Johansson <pettjoha@kth.se>"]
description = "Create substrates and output to GROMOS formatted files"

[dependencies]
ansi_term = "^0.9.0"
clap = "~2.23.0"
