[package]
name = "create_graphene"
version = "0.2.2"
authors = ["Petter Johansson <pettjoha@kth.se>"]
description = "Create substrates and output to GROMOS formatted files"

[dependencies]
clap = "2.22"
