[package]
name = "grafen"
version = "0.3.1"
authors = ["Petter Johansson <pettjoha@kth.se>"]
description = "Create graphene and other substrates for use in molecular dynamics simulations."

[dependencies]
ansi_term = "^0.9.0"
clap = "~2.23.0"
